name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Build
      run: |
        xcodebuild -project "Window Glue.xcodeproj" \
                   -scheme "Window Glue" \
                   -configuration Release \
                   -archivePath "Window Glue.xcarchive" \
                   archive
    
    - name: Export Archive
      run: |
        xcodebuild -exportArchive \
                   -archivePath "Window Glue.xcarchive" \
                   -exportPath "export" \
                   -exportOptionsPlist "export.plist"
    
    - name: Create Export Options Plist
      run: |
        cat > export.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>method</key>
            <string>developer-id</string>
            <key>teamID</key>
            <string>\${{ secrets.TEAM_ID }}</string>
        </dict>
        </plist>
        EOF
    
    - name: Zip App
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd export
        zip -r "Window Glue.zip" "Window Glue.app"
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: export/Window Glue.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}